[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_internal_expect_revert = true
fuzz_runs = 10000

[profile.default.fmt]
    # Single-line vs multi-line statement blocks
    single_line_statement_blocks = "preserve"  # Options: "single", "multi", "preserve"
    # Formatting style for long function headers
    multiline_func_header = "attributes_first"  # Options: "attributes_first", "params_first", "all"
    # Sort import statements alphabetically
    sort_imports = false  
    # Maximum line length where formatter will wrap the line
    line_length = 100  # Default: 120
    # Number of spaces per indentation level
    tab_width = 4  # Default: 4
    # Whether to print spaces between brackets
    bracket_spacing = true  
    # Style of uint/int256 types
    int_types = "long"  # Options: "long", "short", "preserve"
    # Quotation mark style
    quote_style = "double"  # Options: "double", "single", "preserve"
    # Style of underscores in number literals
    number_underscore = "thousands"  # Options: "preserve", "thousands", "remove"
    # Whether or not to wrap comments at line_length
    wrap_comments = false  
    # List of files to ignore during formatting (can use glob patterns)
    ignore = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
